name: VCBNotificationRebuild

options:
  deploymentTarget:
    iOS: "15.6"

targets:
  VCBNotificationRebuild:
    type: application
    platform: iOS

    sources:
      - VCBNotificationRebuildApp.swift

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.VCBNotificationRebuild
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_CFBundleDisplayName: "VCB Notification"
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
